### ISSUE TITLE
Users' full names containing non-ASCII characters breaks Boxen::Config

### ISSUE THREAD

**Issue by dgoodlad** [boxen/boxen#150] opened 2014-05-21 14:46 UTC
For example, @mislav's full name, Mislav Marohnić, causes failures when Boxen::Config tries to load config.json.

**Comment by seanknox** [comment] 2015-03-22 19:30
@indirect I couldn't reproduce this. Is it still an issue for you?

**Comment by indirect** [comment] 2015-03-22 23:53
I have no idea if it's a problem with the latest boxen still, sorry.

**Comment by seanknox** [comment] 2015-03-23 00:41
No worries. Going to close this.

**Closed by seanknox** 2015-03-23 00:41 UTC
Labels: bug

**Comment by mislav** [comment] 2015-03-23 08:35
@seanknox If someone is forking `boxen/our-boxen`, this is fixed for them in https://github.com/boxen/our-boxen/pull/448

**Comment by indirect** [comment] 2015-03-23 20:32
The lock screen message requires a completely different byte encoding scheme, so I doubt this is fixed in general:

```puppet
  # We can't use ::osx::recovery_message because:
  # 1) defaults read can't handle UTF-8. é input becomes either
  #    \U00e9 (if read by file) or \351 (if read by key)
  #    PlistBuddy inexplicably has no problem with UTF-8.
  $recovery_message = "André Arko  714-785-0767  andre@arko.net  @indirect"
  $plist_cmd = "/usr/libexec/PlistBuddy /Library/Preferences/com.apple.loginwindow.plist"
  exec { 'Set OS X Recovery Message':
    command => "$plist_cmd -c 'Add :LoginwindowText string \"$recovery_message\"'",
    unless  => "$plist_cmd -c 'Print :LoginwindowText' | grep '^$recovery_message$'",
    user    => "root",
    notify => [
      Exec['Refresh system kext cache'],
      Exec['Refresh CoreStorage EFI Cache']
    ]
  }

  # 2) nvram good-samaritan-message percent-encodes é into %c3%a9
  $nvram_value = "Andr%c3%a9 Arko  714-785-0767  andre@arko.net  @indirect"
  exec { 'Set OS X Recovery Message NVRAM Variable':
    command => "nvram good-samaritan-message='${nvram_value}'",
    unless  => "nvram good-samaritan-message | cut -c24- | grep '^${nvram_value}$'",
    user    => "root"
  }
  
  # The CoreStorage kext cache needs to be updated so the recovery message
  # is displayed on the FDE pre-boot screen.
  #
  # The CS cache can be updated directly by touching $eficachedir, if it exists.
  # Otherwise you will need to touch $kextdir to generate it.
  $eficachedir = '/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations'
  $kextdir     = '/System/Library/Extensions'
  exec { 'Refresh system kext cache':
      command     => "/usr/bin/touch ${kextdir}",
      creates     => $eficachedir,
      refreshonly => true,
      user        => root
  }

  exec { 'Refresh CoreStorage EFI Cache':
      command     => "/usr/bin/touch ${eficachedir}",
      onlyif      => "test -d ${eficachedir}",
      refreshonly => true,
      user        => root
  }
```
